### ISSUE TITLE
train data loading issue (opencv 4.6)

### ISSUE THREAD

**Issue by czarmanu** [samleoqh/MSCG-Net#18]
While running the command:
PYTHONPATH={PWD}/..:${PYTHONPATH} CUDA_VISIBLE_DEVICES=0 python3 ./tools/train_R50.py 

I get the following error:

train set ------- 56944
val set --------- 18334
---curr_iter: 0, num_iter per epoch: 5695---
[ WARN:0@3.167] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/pf/pfstaff/projects/mtom/mTom_Sat_Data_Fusion/Comparison/supervised/Agriculture-Vision-2021/train/gt/LWJ3IKMP1_9919-3215-10431-3727.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "./tools/train_R50.py", line 259, in <module>
    main()
  File "./tools/train_R50.py", line 113, in main
    for i, (inputs, labels) in enumerate(train_loader):
  File "/scratch/manu/MSCG-Net-master/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/scratch/manu/MSCG-Net-master/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/scratch/manu/MSCG-Net-master/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/manu/MSCG-Net-master/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/manu/MSCG-Net-master_selftrained/data/AgricultureVision/loader.py", line 53, in __getitem__
    label = imload(self.mask_files[idx], gray=True, scale_rate=self.scale)
  File "/scratch/manu/MSCG-Net-master_selftrained/data/augmt.py", line 59, in imload
    image = np.asarray(image, dtype='uint8')
  File "/scratch/manu/MSCG-Net-master/venv/lib/python3.6/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Is it due to opencv version compatibility?. I use version 4.6
I tried with other previous versions (3.4.0.21) but not successful.

**Comment by czarmanu** [comment]
Reason: I was using the 2021 version of the Agriculture vision dataset instead of 2020 version
