### ISSUE TITLE
How to print accuracy in test_submission.py.?

### ISSUE THREAD

**Issue by mukultater** [samleoqh/MSCG-Net#8]

**Comment by mukultater** [comment]
How to print accuracy in test submission.py.?

**Comment by samleoqh** [comment]
test_submission only produces predictions without ground-truth files, so if you like to see the acc/iou metrics, you will need to submit them to https://competitions.codalab.org/competitions/23732?secret_key=dba10d3a-a676-4c44-9acf-b45dc92c5fcf#results

**Comment by mukultater** [comment]
Line 143 in test_submission.py, giving error..
How to resolve this and call this function "def metrics(predictions, gts, label_values=land_classes):".?


I am trying to call this function.
Share a solution for this.

**Comment by samleoqh** [comment]
To use metrics() function, you have to gts - the ground truths data. 
You may want to use it to evaluate the val set, if so you could refer to evaluate() function defined in lib/utils/measure.py, and it's used like

`acc, acc_cls, mean_iu, fwavacc, f1 = evaluate(predictions_all, gts_all, train_args.nb_classes) # line 191, train_R50.py 
`

**Comment by wanzhixiao** [comment]
In which source file is multi perspective embodied?

**Comment by czarmanu** [comment]
Are the following enough to print the metrics such as confusion matrix, accuracy, f1score etc?

in test_submission.py, add a new line:
prepare_gt(TEST_ROOT_FOR_GT_ONLY) , where TEST_ROOT_FOR_GT_ONLY = 'dataset/test/'

and comment out the following lines: 
96, 98, 102, 140, 143, 144

**Comment by czarmanu** [comment]
After these changes, while running test_submission.py :

Traceback (most recent call last):
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 241, in <module>
    main()
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 42, in main
    tta_real_test(nets, stride=600, batch_size=1,
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 101, in tta_real_test
    test_images, test_labels = (loadtestimg(test_set))
ValueError: too many values to unpack (expected 2)

**Comment by samleoqh** [comment]
There is no labels provided for test set, so you can not use prepare_gt() for it. test_submission can not computer accuracy/F1 etc

**Comment by czarmanu** [comment]
I am working now on a new test dataset with labels (in the required format). Is is possible to compute the metrics (with current code) since I have labels?

**Comment by samleoqh** [comment]
The current test_submission.py didn't provide evaluation. You might need to write some code youself to compute the accuracy If you test set has GT files, you can call the function `evaluate(predictions, gts, num_classes)` provided in the file`/lib/utils/measure.py`, then you will get all supported scores.

**Comment by samleoqh** [comment]
An example code for [test_with_ground_truth](https://github.com/samleoqh/DDCM-Semantic-Segmentation-PyTorch/blob/master/tools/test.py). you can modify it according to your case.

**Comment by czarmanu** [comment]
after modification, i am getting a 'key' error  while reading the gt as follows:
test_labels = (np.asarray(io.imread(label), dtype='uint8') for label in test_set[GT])

Traceback (most recent call last):
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 255, in <module>
    main()
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 43, in main
    tta_real_test(nets, stride=600, batch_size=1,
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 106, in tta_real_test
    test_labels = (np.asarray(io.imread(label), dtype='uint8') for label in test_set[GT])
KeyError: 'gt'

**Comment by czarmanu** [comment]
While I try the following modification:

test_labels = (np.asarray(io.imread(label), dtype='uint8') for label in test_set[GT])

for img, id, gt in tqdm(zip(test_files, idlist, test_labels), total=len(test_set[GT]), leave=False):


The following error:

Traceback (most recent call last):
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 260, in <module>
    main()
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 43, in main
    tta_real_test(nets, stride=600, batch_size=1,
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 131, in tta_real_test
    for img, id, gt in tqdm(zip(test_files, idlist, test_labels), total=len(test_set[GT]), leave=False):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/notebook.py", line 222, in __iter__
    for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/scratch/manu/MSCG-Net-master_selftrained/./tools/test_submission.py", line 106, in <genexpr>
    test_labels = (np.asarray(io.imread(label), dtype='uint8') for label in test_set[GT])
  File "/usr/lib/python3/dist-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/lib/python3/dist-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/imageio/core/functions.py", line 221, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/lib/python3/dist-packages/imageio/core/functions.py", line 136, in get_reader
    format = formats.search_read_format(request)
  File "/usr/lib/python3/dist-packages/imageio/core/format.py", line 694, in search_read_format
    if format.can_read(request):
  File "/usr/lib/python3/dist-packages/imageio/core/format.py", line 195, in can_read
    return self._can_read(request)
  File "/usr/lib/python3/dist-packages/imageio/plugins/dicom.py", line 93, in _can_read
    with open(filename, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/core'

**Comment by czarmanu** [comment]
The above issue solved when i used the following to read labels:
test_labels = (loadgt(test_set))
